services:
  libretranslate:
    container_name: libretranslate
    image: libretranslate/libretranslate:latest-cuda # Utilise l'image avec support CUDA
    ports:
      - "5001:5000" # Mappe le port 5001 de l'hôte au port 5000 du conteneur
    environment:
      - LT_CUDA=true # Active l'utilisation de CUDA
      - LT_LANGUAGE=en,fr,jp # Exemple de langues à charger (vous pouvez ajuster)
      # Ajoutez d'autres variables d'environnement si nécessaire, par exemple pour les API keys si vous utilisez des modèles externes
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all # Utilise tous les GPUs disponibles, ou spécifiez un nombre
              capabilities: [gpu] # Indique que le conteneur a besoin d'accès au GPU
    volumes:
      - libretranslate_data:/app/data # Pour persister les données, comme les modèles téléchargés
  # argos-translate:
  #   build:
  #     context: ./argos-image
  #     dockerfile: Dockerfile
  #   ports:
  #     - "5000:5000"
  #   volumes:
  #     - argos-data:/root/.local/share/argos-translate

volumes:
  # argos-data:
  libretranslate_data: